[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flwr-dev"
version = "1.0.0"
requires-python = ">=3.9"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
description = "Small utility compiling useful scripts"
license = "Apache-2.0"
dependencies = [
    "typer",
    "grpcio-tools==1.60.0",
    "protobuf>=4.25.2,<5.0.0",
    "mypy-protobuf==3.2.0",
    "types-protobuf==3.19.18",
    "black==24.2.0",
    "PyGithub==2.1.1",
    "tomli>=2.0.1,<3.0.0",
]
packages = [{ include = "flwr_dev", from = "." }]

[project.scripts]
flwr-dev = "flwr_dev.app:cli"
