blank_issues_enabled: false
contact_links:
  - name: Slack Channel
    url: https://flower.ai/join-slack
    about: Connect with other Flower users and contributors and discuss with them or ask them questions.
  - name: Question/Discussion
    url: https://discuss.flower.ai/
    about: Join the Flower Discuss Forum and ask about new features or general questions. 